config/routes.rb
Moneymaker::Application.routes.draw do

  match 'kapsules/:type' => 'kapsules#index', :type => /popular|recent|mustsee/, :as => :kapsules
  match 'kpoint' => 'kpoint_integration#index', :as => :callback

  root :to => 'home#index'

end

app/models/access_token.rb
class AccessToken
  @@current = nil
  def self.current
    @@current
  end

  def self.current= access_token
    @@current = access_token
  end

  def initialize(token)
    @token = token
  end

  def token
    @token
  end
end

app/models/kapsule.rb
require 'rubygems'
require 'rest_client'
require 'json'
require 'ostruct'

class Kapsule < OpenStruct
  class << self
    ['popular', 'recent', 'mustsee'].each do |type|
      send :define_method, "get_#{type}".to_sym do
        response = RestClient.get("http://#{APP_CONFIG['kpoint_host']}/api/v1/xapi/kapsules/#{type}?first=0&max=10&oauth_token=#{AccessToken.current.token}")
        response_hash = JSON.parse(response)
        response_hash["list"].collect{|k| Kapsule.new(k)}
      end
    end
  end


  def initialize(attribute_hash={})
    super(attribute_hash)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_access_token

  protected
  def access_token
    cookies[:access_token]
  end

  def access_granted?
    !AccessToken.current.nil?
  end

  def kpoint_host
    APP_CONFIG["kpoint_host"]
  end

  def oauth_client_id
    APP_CONFIG["client_id"]
  end

  def access_denied?
    cookies[:access_denied] == "true"
  end

  def requires_oauth_access_token
    (render :status => :forbidden, :text => "Forbidden") and return if access_denied?
    return if access_granted?
    redirect_url = callback_url
    cookies[:requested_url] = request.fullpath
    redirect_to("https://#{kpoint_host}/api/v1/oauth2/authorize?response_type=token&client_id=#{oauth_client_id}&redirect_uri=#{URI.encode(redirect_url)}")
  end

  private
  def set_access_token
    AccessToken.current = (access_token.nil? ? nil : AccessToken.new(access_token))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kapsules_controller.rb
class KapsulesController < ApplicationController
  before_filter :requires_oauth_access_token

  def index
    @kapsules = Kapsule.send "get_#{type}"
  end

  private
  def type
    params[:type]
  end
end

app/controllers/kpoint_integration_controller.rb
class KpointIntegrationController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.haml
#links
  - ['popular', 'recent', 'mustsee'].each do |type|
    %span.link-to-listing
      = link_to "#{type.camelize} Kapsules", kapsules_path(:type => type)

app/views/kapsules/index.html.haml
#kapsules
  - @kapsules.each do |kapsule| 
    #kapsule.kapsule
      #thumb
      %h3
        = kapsule.displayname
      %span.owner
        = "By #{kapsule.owner_displayname}"

app/views/kpoint_integration/index.html.haml
=javascript_include_tag "kpoint"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kappuccino</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>